### ISSUE TITLE
请问下数据集能不能分享下

### ISSUE THREAD

**Issue by gumanchang** [beyondguo/LLM-Tuning#1]

**Comment by beyondguo** [comment]
您好，数据暂时还在优化过程中，暂时不会分享，但后面有一个系统的计划会开放多种任务的微调数据和微调参数。目前的话您可以自己爬取一些新闻然后使用ChatGPT来标注，或者您有新闻数据的话也可以发给我来帮你用ChatGPT标注。

**Comment by gumanchang** [comment]
那我使用一些开源的数据集alpaca_data_zh_51k.json这样的，也可以训练的吧，不一定非得新闻数据吧

**Comment by beyondguo** [comment]
是的，完全可以，只是不同的训练数据可能需要指定的字段名。比如你的json文件中，模型输入字段是"instruction"，输出字段是"output"，那么就需要在`tokenize.sh`中设置：
```shell
    --prompt_key instruction \
    --target_key output \
```
