### ISSUE TITLE
如何评估finetune过程中模型的性能？

### ISSUE THREAD

**Issue by dxyzx0** [beyondguo/LLM-Tuning#13]
一般在finetune的时候，每个`epoch`或者固定`xx steps`后都会在`eval_dataset`上做一次性能的评估，这里是直接无需做此评估，还是说出于其他原因没有进行评估？

谢谢！

**Comment by beyondguo** [comment]
代码里面省去了这一步，因为目前我自己只关注微调训练的稳定性，所以看看train set上的loss就够了。当然你额外添加一个eval set肯定更好，实现上也只需在Trainer部分加一行即可。

**Comment by dxyzx0** [comment]
感谢！
还想问个问题：如何衡量训练的稳定性呀？就是能够一直train下去不会报错么？
