### ISSUE TITLE
请教一下显存问题

### ISSUE THREAD

**Issue by Jamine-W** [beyondguo/LLM-Tuning#25]
你好，我使用两张3090基于chatglm2-6b进行lora微调，batch_size设置为14，一开始跑的时候单卡显存才占18个g，但是跑到几百个step的时候就显存溢出了，请问这要怎么解决呢？

**Comment by beyondguo** [comment]
我80G的卡都不敢随随便便开batch_size 14😶

**Comment by Jamine-W** [comment]
> 
啊是这样吗，但是我一开始是可以跑的呢，跑到800个step的时候爆内存了，为什么内存一直会涨呢

**Comment by wuxiaobo** [comment]
我也遇到这样的问题，内存一直在增加直到OOM
