### ISSUE TITLE
感觉说的不是很明白

### ISSUE THREAD

**Issue by Hzzhang-nlp** [beyondguo/LLM-Tuning#3]
比如模型是直接下载下来还是直接运行代码，就会下载模型；
那个data，可以自己生成还是需要自己准备

**Comment by beyondguo** [comment]
提issue不是这么提的吧。建议先把最基础的huggingface基础用法熟悉一下，data的部分，我README部分的教程写的应该很清楚了，需要你自己准备，这个仓库主要负责训练。

**Comment by Hzzhang-nlp** [comment]
好吧，是我说话表达方式不对，抱歉
