### ISSUE TITLE
TORCH_USE_CUDA_DSA

### ISSUE THREAD

**Issue by Mrjude** [beyondguo/LLM-Tuning#34]
finetune，没有出现过CUDA error吗？device-side assert triggered的问题

**Comment by beyondguo** [comment]
提供完整信息再reopen

**Comment by Mrjude** [comment]
环境是多卡的V100服务器，我用单卡跑，是按照repo的代码跑，就会出现 CUDA error device-side assert triggered的问题

**Comment by Smilefish1** [comment]
> 环境是多卡的V100服务器，我用单卡跑，是按照repo的代码跑，就会出现 CUDA error device-side assert triggered的问题

同学，解决了吗，我也遇到这个问题了，我也是双卡的V100
