### ISSUE TITLE
加载数据集报错

### ISSUE THREAD

**Issue by endlesstalking** [beyondguo/LLM-Tuning#47]
在huggingface上下载yitingxie/rlhf-reward-datasets数据集后，启动基于baichuan-7b的RL训练，

会报如下错误，辛苦作者帮忙看下，感谢
![image](https://github.com/beyondguo/LLM-Tuning/assets/23204422/759642b2-cd10-4f9b-852d-1d8ebcf470ef)

**Comment by beyondguo** [comment]
数据保存到对应文件夹了吗？你看看reward modeling部分的代码，就清楚为啥报这个错误了。
